/**
 * Mock data fallback — used when the Next.js API routes are unreachable.
 * All shapes mirror the real API response types exactly.
 *
 * Timeline: 40 events — research-verified historical data covering 687 years of Kashmir history.
 */
import type {
  TimelineEvent, NewsArticle, SocialPost, TimestampMarker,
} from '@/types/api';

export const MOCK_TIMELINE: TimelineEvent[] = [
  {
    year: 1339,
    title: 'Shah Mir Dynasty Founded',
    category: 'cultural',
    description: 'Shah Mir establishes the first Muslim sultanate in Kashmir, ending centuries of Hindu and Buddhist rule. For 222 years, six successive dynasties will govern the valley, weaving Islamic traditions into the Kashmiri cultural fabric that endures to this day.',
    lat: 34.09, lng: 74.80, place: 'Srinagar',
  },
  {
    year: 1586,
    title: 'Mughal Conquest of Kashmir',
    category: 'cultural',
    description: "Emperor Akbar annexes Kashmir into the Mughal Empire after two earlier failed attempts. His son Jahangir later calls it 'paradise on earth.' The Shalimar and Nishat Bagh gardens are built on Dal Lake. Beauty becomes an instrument of empire.",
    lat: 34.08, lng: 74.79, place: 'Srinagar',
  },
  {
    year: 1752,
    title: 'Afghan Durrani Rule Begins',
    category: 'political',
    description: "Ahmad Shah Durrani's Afghan empire wrenches Kashmir from the declining Mughals. Six decades of Afghan rule follow — remembered in Kashmir as a period of harsh extraction, forced conversions, and deep impoverishment. The memory shapes Kashmiri identity.",
    lat: 34.09, lng: 74.80, place: 'Kashmir Valley',
  },
  {
    year: 1819,
    title: 'Sikh Conquest under Ranjit Singh',
    category: 'political',
    description: "Ranjit Singh's Sikh Empire takes Kashmir from the Afghans. The valley becomes the empire's prized summer territory. Sikh rule lasts 27 years — until the British defeat the Sikh armies in two Anglo-Sikh wars and everything changes.",
    lat: 34.08, lng: 74.78, place: 'Kashmir Valley',
  },
  {
    year: 1846,
    title: 'Treaty of Amritsar: A People Sold',
    category: 'political',
    description: "After defeating the Sikhs, the British sell Kashmir and its people to Dogra ruler Gulab Singh for 75 lakh Nanakshahi rupees under the Treaty of Amritsar. A people traded like property. The Dogra dynasty begins its century of rule. Kashmiris are never asked.",
    lat: 32.73, lng: 74.87, place: 'Jammu',
    doc: {
      kind: 'Foundational Treaty',
      name: 'Treaty of Amritsar (1846)',
      date: '16 March 1846',
      desc: "The 'sale deed' of Kashmir. Ten articles transferred all the hilly territory east of the Indus and west of the Ravi to Gulab Singh and his heirs in independent possession, under British suzerainty, for 7.5 million rupees.",
      source: 'Wikisource',
      url: 'https://en.wikisource.org/wiki/Treaty_of_Amritsar',
    },
  },
  {
    year: 1931,
    title: "Anti-Dogra Uprising; Martyrs' Day",
    category: 'conflict',
    description: "Mass protests erupt against the repressive Dogra regime across the valley. On July 13, Dogra police open fire on a crowd outside Srinagar Central Jail, killing 22 demonstrators. July 13 becomes Kashmir's Martyrs' Day. A young Sheikh Mohammad Abdullah emerges as a political voice of the people.",
    lat: 34.09, lng: 74.80, place: 'Srinagar',
  },
  {
    year: 1939,
    title: 'All J&K National Conference Founded',
    category: 'political',
    description: "Sheikh Mohammad Abdullah transforms the Muslim Conference into the All Jammu & Kashmir National Conference — a secular, cross-community movement against autocratic Dogra rule. The 'Naya Kashmir' manifesto of 1944 envisions land reform, universal education, equal rights. A brief democratic horizon.",
    lat: 34.08, lng: 74.79, place: 'Srinagar',
  },
  {
    year: 1947,
    title: 'Partition & Instrument of Accession',
    category: 'political',
    description: "India and Pakistan gain independence on August 15. Maharaja Hari Singh — a Hindu ruler of a Muslim-majority state — delays signing accession to either nation. Pakistani tribal militias backed by the army invade on October 22. Singh signs the Instrument of Accession to India on October 26. Indian troops airlift into Srinagar. The wound that will not close opens.",
    lat: 34.09, lng: 74.80, place: 'Srinagar',
    doc: {
      kind: 'Accession Instrument',
      name: 'Instrument of Accession (Jammu & Kashmir)',
      date: '26 October 1947',
      desc: "The legal document by which Jammu & Kashmir acceded to the Dominion of India under the Indian Independence Act 1947, signed by Maharaja Hari Singh and accepted by Governor-General Mountbatten. It remains the cornerstone of India's legal claim to the state.",
      source: 'Wikisource',
      url: 'https://en.wikisource.org/wiki/Instrument_of_Accession_(Jammu_and_Kashmir)',
    },
  },
  {
    year: 1948,
    title: 'First Kashmir War; UN Plebiscite Never Held',
    category: 'conflict',
    description: "The first Indo-Pakistani war over Kashmir continues through winter. The UN Security Council passes Resolution 47 on April 21, ordering a ceasefire and a free plebiscite to let Kashmiris decide their future. India and Pakistan agree. A ceasefire takes effect on January 1, 1949. The Ceasefire Line divides the territory. The plebiscite is never held.",
    lat: 34.08, lng: 74.08, place: 'Uri Sector',
    doc: {
      kind: 'UN Resolution',
      name: 'UNSC Resolution 47 (1948)',
      date: '21 April 1948',
      desc: 'The resolution that set out the conditions for a UN-supervised plebiscite in Jammu & Kashmir. Its sequencing — Pakistani withdrawal first — became the central deadlock. Both sides have cited it ever since to opposite ends.',
      source: 'UN Digital Library',
      url: 'https://digitallibrary.un.org/record/112000',
    },
  },
  {
    year: 1949,
    title: 'Article 370 Grants Special Autonomous Status',
    category: 'political',
    description: "Article 370 is incorporated into the Indian Constitution, granting Jammu & Kashmir a unique special status. J&K has its own constitution, its own flag, and exclusive jurisdiction over all matters except defence, foreign affairs, finance, and communications. Described as a 'temporary provision' in 1949 — it lasts 70 years.",
    lat: 34.08, lng: 74.79, place: 'Srinagar',
    doc: {
      kind: 'Constitutional Article',
      name: 'Article 370 of the Constitution of India',
      date: 'In force 17 November 1952 (as drafted 1949)',
      desc: "The provision granting Jammu & Kashmir special autonomous status within the Indian Union, limiting Parliament's legislative reach and preserving the state's separate constitution. It governed the state's relationship with India until 2019.",
      source: 'Constitution of India',
      url: 'https://www.constitutionofindia.net/articles/article-370-temporary-provisions-with-respect-to-the-state-of-jammu-and-kashmir/',
    },
  },
  {
    year: 1953,
    title: 'Sheikh Abdullah Arrested',
    category: 'political',
    description: "Prime Minister Sheikh Abdullah is dismissed and arrested, accused of conspiring with foreign powers and flirting with independence. He will spend most of the next 22 years imprisoned or in political exile. The man who led the valley into India's embrace is removed from it. The democratic promise of Kashmir's politics begins to hollow.",
    lat: 34.09, lng: 74.80, place: 'Srinagar',
  },
  {
    year: 1957,
    title: "J&K's Own Constitution Adopted",
    category: 'political',
    description: "Jammu & Kashmir adopts its own state constitution on January 26, cementing a unique political arrangement within India. The state assembly endorses accession. Pakistan and the UN contest the legitimacy of this move without a plebiscite. The question of self-determination is politically sealed — not resolved.",
    lat: 34.08, lng: 74.79, place: 'Srinagar',
  },
  {
    year: 1960,
    title: 'Indus Waters Treaty Signed',
    category: 'political',
    description: 'After nine years of World Bank mediation, India and Pakistan divide the Indus river system: the eastern rivers (Ravi, Beas, Sutlej) to India, the western rivers (Indus, Jhelum, Chenab) largely to Pakistan. The treaty survives every subsequent war — until 2025.',
    lat: 24.86, lng: 67.01, place: 'Karachi',
    doc: {
      kind: 'Water Treaty',
      name: 'Indus Waters Treaty (1960)',
      date: '19 September 1960',
      desc: 'The World Bank–brokered treaty allocating the six rivers of the Indus basin between India and Pakistan. Long held as a model of cooperation surviving three wars, it was placed in abeyance by India in April 2025 following the Pahalgam attack.',
      source: 'World Bank',
      url: 'https://www.worldbank.org/en/region/sar/brief/fact-sheet-the-indus-waters-treaty-1960-and-the-role-of-the-world-bank',
    },
  },
  {
    year: 1962,
    title: 'Sino-Indian War; Aksai Chin Lost',
    category: 'conflict',
    description: "China's PLA launches surprise attacks on India in the Western and Eastern Himalayas. In the western sector, China seizes Aksai Chin — 37,244 sq km of high-altitude plateau that it had quietly been building a strategic road through since the 1950s, undetected by India. India is routed. China retains Aksai Chin. The third dimension of Kashmir's contested sovereignty takes permanent shape.",
    lat: 34.90, lng: 78.50, place: 'Aksai Chin / Ladakh',
  },
  {
    year: 1963,
    title: 'Hazratbal Relic Stolen; Valley Erupts',
    category: 'cultural',
    description: "The Moi-e-Muqqadas — a hair of the Prophet Mohammad — is stolen from the Hazratbal shrine in Srinagar on December 27. Mass protests paralyse the valley for weeks. The relic mysteriously reappears on January 4, 1964. The crisis deepens mistrust of the Indian state and reinforces Kashmiri Muslim identity as a political force.",
    lat: 34.13, lng: 74.83, place: 'Hazratbal, Srinagar',
  },
  {
    year: 1965,
    title: 'Second Kashmir War; Operation Gibraltar',
    category: 'conflict',
    description: "Pakistan launches Operation Gibraltar, infiltrating thousands of trained guerrillas across the Ceasefire Line to spark an uprising that never materialises — Kashmiris do not join. Full-scale war erupts. The Tashkent Declaration restores pre-war positions. Nothing changes. Everything hardens. The belief that military force can resolve Kashmir is reaffirmed — wrongly — on both sides.",
    lat: 34.08, lng: 74.08, place: 'Uri / Chamb Sector',
  },
  {
    year: 1966,
    title: 'Tashkent Declaration',
    category: 'political',
    description: 'Mediated by the Soviet Union, Indian PM Shastri and Pakistani President Ayub Khan sign the Tashkent Declaration, agreeing to withdraw to pre-war positions and restore relations. Shastri dies in Tashkent hours after signing. The Kashmir question is left entirely untouched.',
    lat: 41.30, lng: 69.24, place: 'Tashkent, USSR',
    doc: {
      kind: 'Peace Declaration',
      name: 'Tashkent Declaration (1966)',
      date: '10 January 1966',
      desc: 'The Soviet-brokered agreement ending the 1965 war, restoring the pre-war boundary and ordering prisoner exchanges. It settled the fighting but left the Kashmir question untouched.',
      source: 'UN Peacemaker',
      url: 'https://peacemaker.un.org/india-pakistan-tashkent-declaration66',
    },
  },
  {
    year: 1971,
    title: 'Bangladesh War; Pakistan Fractures',
    category: 'political',
    description: "India goes to war with Pakistan in support of Bangladesh's independence. Pakistan is militarily crushed on the eastern front. 93,000 Pakistani soldiers surrender. Bangladesh is born. The political equation in South Asia shifts permanently. Pakistan's strategic humiliation will reshape its Kashmir policy — greater covert involvement, greater proxy pressure — for decades.",
    lat: 32.73, lng: 74.86, place: 'Jammu Front',
  },
  {
    year: 1972,
    title: 'Shimla Agreement; Line of Control Named',
    category: 'political',
    description: "India and Pakistan sign the Shimla Agreement on July 2. The former UN Ceasefire Line is renamed the Line of Control. Both sides agree to resolve the Kashmir issue bilaterally — without third-party intervention — through peaceful negotiations. The UN plebiscite is effectively buried. The LoC becomes the de facto border that neither side accepts as permanent.",
    lat: 32.73, lng: 74.86, place: 'Jammu & Kashmir',
    doc: {
      kind: 'Bilateral Agreement',
      name: 'Simla Agreement (1972)',
      date: '2 July 1972',
      desc: "Signed after the 1971 war, it committed both nations to resolve their differences bilaterally and peacefully, converting the Ceasefire Line into the Line of Control. India has long cited it to keep Kashmir a bilateral matter. Pakistan placed it in abeyance in April 2025.",
      source: 'UN Peacemaker',
      url: 'https://peacemaker.un.org/india-pakistan-simla-agreement72',
    },
  },
  {
    year: 1984,
    title: 'Operation Meghdoot; Siachen Glacier Seized',
    category: 'conflict',
    description: "India launches Operation Meghdoot on April 13 — airlifting troops to the Siachen Glacier at up to 6,000m altitude, pre-empting a similar Pakistani operation. India secures the Saltoro Ridge. Pakistan responds militarily. The world's highest and coldest battlefield is born. Over the following decades, both armies lose more soldiers to avalanches, altitude sickness, and frostbite than to enemy fire.",
    lat: 35.42, lng: 77.10, place: 'Siachen Glacier',
  },
  {
    year: 1987,
    title: 'Disputed Elections: Democracy Betrayed',
    category: 'political',
    description: "State assembly elections are widely alleged to be rigged in favour of the ruling National Conference-Congress alliance. Muslim United Front candidates — including future militant commanders — who won at the polls find their victories reversed and themselves arrested. A generation that had committed to the democratic path turns toward the gun. The 1987 elections are widely cited as the insurgency's ignition switch.",
    lat: 34.09, lng: 74.80, place: 'Srinagar',
  },
  {
    year: 1989,
    title: 'Armed Insurgency Erupts',
    category: 'conflict',
    description: "The Jammu & Kashmir Liberation Front launches armed operations demanding azadi. The kidnapping of Rubaiya Sayeed — daughter of Union Home Minister Mufti Mohammed Sayeed — shocks India into releasing five militants. Multiple armed groups emerge. The valley tips into full insurgency. The Indian Army and paramilitary forces pour in. An estimated 70,000–100,000 people will die over the following three decades.",
    lat: 34.08, lng: 74.80, place: 'Kashmir Valley',
  },
  {
    year: 1990,
    title: 'Kashmiri Pandit Exodus',
    category: 'humanitarian',
    description: "In the winter of 1990, between 100,000 and 250,000 Kashmiri Pandits — the valley's indigenous Hindu minority present for millennia — flee their homes under threat. Targeted killings of prominent Pandits, mosque broadcasts urging departure, and a failure of state protection create mass panic. Governor Jagmohan imposes direct rule. AFSPA gives security forces sweeping, unaccountable powers. The Pandits become refugees in their own country — and the wound between communities does not heal.",
    lat: 34.09, lng: 74.79, place: 'Kashmir Valley',
  },
  {
    year: 1995,
    title: 'Charar-e-Sharif Fire; Western Hostages',
    category: 'conflict',
    description: "The 14th-century Charar-e-Sharif shrine — sacred to Kashmiri Sufis for six centuries — burns to the ground during a months-long standoff between militants and Indian security forces. Each side blames the other. That same year, the Al-Faran militant group kidnaps six Western trekkers in the Pahalgam mountains. One escapes, one is beheaded and found, four are never seen again.",
    lat: 33.95, lng: 74.72, place: 'Charar-e-Sharif',
  },
  {
    year: 1999,
    title: 'Lahore Declaration',
    category: 'political',
    description: "Prime Ministers Vajpayee and Sharif sign the Lahore Declaration, committing to peace and nuclear restraint after both states had tested weapons in 1998. The Kargil intrusion, which begins months later, undoes the fragile optimism.",
    lat: 31.52, lng: 74.36, place: 'Lahore',
    doc: {
      kind: 'Peace Declaration',
      name: 'Lahore Declaration (1999)',
      date: '21 February 1999',
      desc: "A bilateral commitment to intensify dialogue, reduce nuclear risk and resolve Kashmir peacefully, signed during Vajpayee's historic bus diplomacy to Lahore. The Kargil intrusion months later effectively buried it.",
      source: 'UN Peacemaker',
      url: 'https://peacemaker.un.org/indiapakistan-lahoredeclaration99',
    },
  },
  {
    year: 1999,
    title: 'Kargil War',
    category: 'conflict',
    description: "Pakistani soldiers and Lashkar-e-Taiba militants secretly cross the LoC during winter and occupy strategic Indian positions in the Kargil hills — some at 5,000m. India responds with Operation Vijay. 527 Indian and an estimated 357–453 Pakistani soldiers are officially killed. The US intervenes diplomatically. Pakistan withdraws. India recaptures nearly all positions. Two nuclear-armed states come to the brink. The world watches.",
    lat: 34.55, lng: 76.13, place: 'Kargil',
  },
  {
    year: 2001,
    title: 'Indian Parliament Attack',
    category: 'conflict',
    description: "On December 13, Lashkar-e-Taiba and Jaish-e-Mohammed operatives attack the Indian Parliament in New Delhi, killing 14 people including all five attackers. India deploys half a million troops to the Pakistani border. Nuclear war fears reach their highest point since the Cold War. International pressure forces de-escalation. Pakistan bans both organisations — temporarily. Kashmir remains the unstated text of the entire crisis.",
    lat: 34.32, lng: 73.88, place: 'LoC / Uri Sector',
  },
  {
    year: 2005,
    title: 'Srinagar–Muzaffarabad Bus Service Reopens',
    category: 'political',
    description: "On April 7, a bus crosses the Line of Control for the first time in 57 years, connecting Srinagar (India) and Muzaffarabad (AJK capital). Passengers — many meeting family members separated since Partition — are photographed weeping at the crossing. Trade routes open briefly. The service carries hope across a line that does not officially acknowledge the people it divides.",
    lat: 34.09, lng: 74.80, place: 'Srinagar',
  },
  {
    year: 2008,
    title: 'Amarnath Land Row; Mass Protests',
    category: 'conflict',
    description: "A proposed transfer of forest land to the Shri Amarnath Shrine Board triggers the largest mass protests in a decade. The valley shuts down completely. On the Pakistani side, parallel protests against Indian rule. Then the Mumbai terror attacks of November 2008 — attributed to Lashkar-e-Taiba — bring India and Pakistan back to the edge. Old anger finds new fuel on both sides.",
    lat: 34.09, lng: 74.80, place: 'Srinagar',
  },
  {
    year: 2010,
    title: 'Summer Unrest; 120 Civilians Killed',
    category: 'conflict',
    description: "Mass protests erupt across the valley after the killing of a teenager in an alleged fake encounter. For three months, stone-throwing youth face live ammunition from Central Reserve Police Force. At least 120 civilians are killed. Curfews last weeks at a time. A generation born after the 1989 insurgency finds its own language of resistance — rock in hand, face covered, running.",
    lat: 34.09, lng: 74.80, place: 'Srinagar & Valley',
  },
  {
    year: 2016,
    title: 'Burhan Wani Killed; A New Generation Rises',
    category: 'conflict',
    description: "On July 8, Indian security forces kill Hizbul Mujahideen commander Burhan Wani — a young, social-media-savvy militant with 70,000 Facebook followers who had made militancy aspirational for a new generation. What follows: 87 days of curfew, the worst in years. Security forces fire pellet guns into crowds at close range. An estimated 600 people are blinded or partially blinded. Wani becomes a symbol for those who grew up after the insurgency.",
    lat: 33.68, lng: 75.15, place: 'South Kashmir',
  },
  {
    year: 2019,
    title: 'Article 370 Revoked; J&K Bifurcated',
    category: 'political',
    description: "On August 5, the Indian Parliament abrogates Article 370 and Article 35A, stripping Jammu & Kashmir of its special status and statehood in a single session. J&K is bifurcated into two Union Territories: Jammu & Kashmir and Ladakh. A complete communications blackout — mobile networks, internet, landlines — seals the valley for months. Thousands are preventively detained, including elected politicians. The world watches from outside.",
    lat: 34.09, lng: 74.80, place: 'Srinagar',
    doc: {
      kind: 'Presidential Order',
      name: 'Constitutional Order C.O. 272 (2019)',
      date: '5 August 2019',
      desc: "The Presidential Order and accompanying parliamentary resolution that rendered Article 370 inoperative, ending Jammu & Kashmir's special constitutional status. Paired with the Reorganisation Act, it dissolved the state.",
      source: 'The Gazette of India',
      url: 'https://egazette.gov.in/',
    },
  },
  {
    year: 2019,
    title: 'J&K Reorganisation Act',
    category: 'political',
    description: 'Parliament splits Jammu & Kashmir into two Union Territories — Jammu & Kashmir (with a legislature) and Ladakh (without one) — under direct central administration. The state loses its statehood. The reorganisation takes effect on 31 October 2019.',
    lat: 28.62, lng: 77.24, place: 'New Delhi',
    doc: {
      kind: 'Act of Parliament',
      name: 'J&K Reorganisation Act, 2019',
      date: '9 August 2019 (effective 31 October 2019)',
      desc: 'The law that downgraded the state of Jammu & Kashmir into two centrally administered Union Territories, ending its statehood and redrawing the administrative map of the region.',
      source: 'India Code',
      url: 'https://www.indiacode.nic.in/handle/123456789/12289',
    },
  },
  {
    year: 2020,
    title: 'New Domicile Laws; Land Rights Changed',
    category: 'political',
    description: "The Indian government introduces new domicile rules allowing non-Kashmiris who have lived in J&K for 15 years — including government employees posted there — to become permanent residents and own land and property. The pre-370 Permanent Resident Certificate system, which restricted land ownership to state subjects, is abolished. Kashmiris call it demographic engineering. India frames it as equality.",
    lat: 34.09, lng: 74.79, place: 'Jammu & Kashmir',
  },
  {
    year: 2021,
    title: 'Delimitation Commission Redraws Constituencies',
    category: 'political',
    description: "The Delimitation Commission redraws J&K's assembly constituencies for the first time in decades. The commission adds six new seats in Jammu and one in Kashmir — critics allege the redrawing favours the Hindu-majority Jammu region at the expense of the Muslim-majority Kashmir Valley. The commission's recommendations become the electoral map for the 2024 elections.",
    lat: 32.73, lng: 74.87, place: 'Jammu',
  },
  {
    year: 2023,
    title: 'Supreme Court Upholds Article 370 Repeal',
    category: 'political',
    description: "A five-judge Constitution Bench unanimously upholds the 2019 abrogation of Article 370 as constitutionally valid, declares it a temporary provision, and orders assembly elections by September 2024 and the eventual restoration of statehood. A landmark judgment on the region's constitutional future.",
    lat: 28.62, lng: 77.24, place: 'New Delhi',
    doc: {
      kind: 'Court Judgment',
      name: 'In re: Article 370 of the Constitution (2023)',
      date: '11 December 2023',
      desc: "The Supreme Court of India's unanimous judgment validating the 2019 abrogation and directing the restoration of statehood and the holding of elections, while recommending a truth and reconciliation process for the region.",
      source: 'Supreme Court of India',
      url: 'https://www.sci.gov.in/',
    },
  },
  {
    year: 2024,
    title: 'First Assembly Elections Since Article 370',
    category: 'political',
    description: "Jammu & Kashmir holds its first assembly elections since the revocation of Article 370 — and the first since it was made a Union Territory in 2019. The National Conference-Congress alliance wins. Omar Abdullah becomes Chief Minister. The restoration of full statehood — promised by the Indian government — remains undelivered. Whether democracy has returned, or its form, is the question the film is still asking.",
    lat: 34.09, lng: 74.80, place: 'Jammu & Kashmir',
  },
  {
    year: 2025,
    title: 'Pahalgam Attack & Operation Sindoor',
    category: 'conflict',
    description: 'On April 22, militants kill 26 tourists at Pahalgam — the deadliest civilian attack in the valley in a quarter-century. India blames Pakistan-backed groups. On May 7, India launches Operation Sindoor, striking targets across Pakistan-administered Kashmir and Pakistan. Four days of exchanges follow before a ceasefire understanding is reached.',
    lat: 34.01, lng: 75.32, place: 'Pahalgam / LoC',
  },
  {
    year: 2025,
    title: 'India Suspends the Indus Waters Treaty',
    category: 'political',
    description: "Following the Pahalgam attack, India puts the 1960 Indus Waters Treaty in abeyance — the first time since it was signed. Pakistan retaliates by suspending the Simla Agreement and closing its airspace to Indian aircraft. Two foundational agreements of South Asian coexistence are placed simultaneously on hold.",
    lat: 28.62, lng: 77.24, place: 'New Delhi',
    doc: {
      kind: 'Government Decision',
      name: 'Cabinet Committee on Security Decision (2025)',
      date: '23 April 2025',
      desc: "India's decision to hold the Indus Waters Treaty in abeyance — the first time since 1960 — alongside diplomatic downgrades following the Pahalgam massacre. Pakistan simultaneously placed the Simla Agreement in abeyance.",
      source: 'Press Information Bureau',
      url: 'https://pib.gov.in/',
    },
  },
  {
    year: 2026,
    title: 'Kashmir — An Unresolved Present',
    category: 'political',
    description: 'Jammu & Kashmir remains a Union Territory awaiting the promised restoration of statehood. The Indus Waters Treaty is still suspended. The territory remains divided among India, Pakistan, and China. The ceasefire line drawn in 1949 still holds. No plebiscite has ever been held. This film was made in this moment.',
    lat: 34.09, lng: 74.80, place: 'Jammu & Kashmir',
  },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: '1',
    title: 'Kashmir Valley Witnesses First Snow of Season in Higher Reaches',
    summary: 'Several mountain passes received fresh snowfall as temperatures dip across the valley. Residents in Gulmarg and Pahalgam report significant accumulation.',
    source: 'Greater Kashmir',
    url: '#',
    published_at: new Date(Date.now() - 1000 * 60 * 43).toISOString(),
    image_url: 'https://images.pexels.com/photos/14651212/pexels-photo-14651212.jpeg?auto=compress&cs=tinysrgb&w=600&q=70',
    category: 'environment',
  },
  {
    id: '2',
    title: 'J&K Government Announces New Infrastructure Projects Across Districts',
    summary: 'Chief Minister Omar Abdullah chairs review meeting on development projects. Focus on road connectivity to remote border villages and broadband expansion.',
    source: 'Kashmir Observer',
    url: '#',
    published_at: new Date(Date.now() - 1000 * 60 * 127).toISOString(),
    category: 'politics',
  },
  {
    id: '3',
    title: 'Human Rights Groups Report Continued Concerns Over Detentions',
    summary: 'International organisations document ongoing cases of administrative detention under the Public Safety Act, calling for greater transparency and independent oversight.',
    source: 'Al Jazeera',
    url: '#',
    published_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    image_url: 'https://images.pexels.com/photos/8303558/pexels-photo-8303558.jpeg?auto=compress&cs=tinysrgb&w=600&q=70',
    category: 'human-rights',
  },
  {
    id: '4',
    title: "Kashmir's Pashmina Weavers Seek Market Access Amid Trade Crisis",
    summary: 'Traditional artisans in Srinagar appeal for government intervention to protect the centuries-old pashmina industry from cheaper synthetic imitations flooding domestic and international markets.',
    source: 'The Wire',
    url: '#',
    published_at: new Date(Date.now() - 1000 * 60 * 380).toISOString(),
    category: 'culture',
  },
  {
    id: '5',
    title: 'Cross-LoC Trade Routes Remain Suspended; Communities Feel the Weight',
    summary: 'Families separated by the Line of Control continue to live with restricted movement and communication. Trade that once supported thousands of livelihoods on both sides remains frozen since 2019.',
    source: 'Dawn',
    url: '#',
    published_at: new Date(Date.now() - 1000 * 60 * 510).toISOString(),
    image_url: 'https://images.pexels.com/photos/8303558/pexels-photo-8303558.jpeg?auto=compress&cs=tinysrgb&w=600&q=70',
    category: 'society',
  },
  {
    id: '6',
    title: 'Youth Employment Crisis Deepens in Kashmir Valley, Report Finds',
    summary: 'A new study by the Institute of Kashmir Studies highlights alarming unemployment figures among educated youth, raising concerns about long-term social stability and political alienation.',
    source: 'Scroll.in',
    url: '#',
    published_at: new Date(Date.now() - 1000 * 60 * 690).toISOString(),
    category: 'economy',
  },
];

export const MOCK_SOCIAL: SocialPost[] = [
  {
    id: '1',
    platform: 'twitter',
    handle: '@kashmirwalla',
    name: 'Kashmir Walla',
    content: 'The mountains do not care about the Line of Control. They were here before the borders were drawn and they will be here after. People deserve the same permanence.',
    likes: 2847, comments: 341, url: '#',
    posted_at: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  },
  {
    id: '2',
    platform: 'instagram',
    handle: '@srinagar.diaries',
    name: 'Srinagar Diaries',
    content: 'Dawn on Dal Lake. The city waking. The mountains watching. Every morning here feels like a gift that could be taken back.',
    image_url: 'https://images.pexels.com/photos/14651212/pexels-photo-14651212.jpeg?auto=compress&cs=tinysrgb&w=500&q=70',
    likes: 5621, comments: 127, url: '#',
    posted_at: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
  },
  {
    id: '3',
    platform: 'twitter',
    handle: '@parveenswani',
    name: 'Parveen Swani',
    content: 'My father used to say: we are not fighting. We are waiting. I am still not sure whether that is better or worse.',
    likes: 1203, comments: 89, url: '#',
    posted_at: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
  },
  {
    id: '4',
    platform: 'instagram',
    handle: '@kashmir.frames',
    name: 'Kashmir Frames',
    content: 'The craftsman at his loom. 40 years, same motion. His son drives a cab in Delhi now. The skill will end with him.',
    image_url: 'https://images.pexels.com/photos/8303558/pexels-photo-8303558.jpeg?auto=compress&cs=tinysrgb&w=500&q=70',
    likes: 3892, comments: 214, url: '#',
    posted_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
  {
    id: '5',
    platform: 'twitter',
    handle: '@dilnawazkhan_jk',
    name: 'Dilnawaz Khan',
    content: 'People ask what it is like to live here. I tell them: imagine being the most beautiful place in the world and having that beauty be the reason for your suffering.',
    likes: 4451, comments: 502, url: '#',
    posted_at: new Date(Date.now() - 1000 * 60 * 445).toISOString(),
  },
  {
    id: '6',
    platform: 'instagram',
    handle: '@kashmir.voices',
    name: 'Kashmir Voices',
    content: 'Three generations in one photograph. Grandfather who remembers before partition. Father who lived through 1989. Daughter who has only known this as normal. Three Kashmirs, one family.',
    image_url: 'https://images.pexels.com/photos/14651212/pexels-photo-14651212.jpeg?auto=compress&cs=tinysrgb&w=500&q=70',
    likes: 7201, comments: 388, url: '#',
    posted_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
  },
];

export const MOCK_TIMESTAMPS: TimestampMarker[] = [
  { timestamp_seconds: 0,    title: 'Prologue — Night Patrol',              description: 'Opens in darkness. A military patrol on a Kashmir road. No context. Just sound, dark, tension.',  chapter: 'Prologue' },
  { timestamp_seconds: 240,  title: 'Chapter One — The Paradise You Did Not Choose', description: 'Kashmir morning. The beauty that makes the darkness worse.',  chapter: 'Origins' },
  { timestamp_seconds: 840,  title: 'Chapter Two — The Line on the Map',    description: 'History arrives. Partition, the Line of Control, the decisions made in rooms far from Kashmir.', chapter: 'Partition' },
  { timestamp_seconds: 1680, title: 'Chapter Three — The Fathers',          description: 'The first father. Then the second. Then the third. The film stays with them.',  chapter: 'Human Stories' },
  { timestamp_seconds: 2520, title: 'Chapter Four — The Armed',             description: 'Militants, soldiers. Both sides of the same argument, both wrong, both right.',  chapter: 'Conflict' },
  { timestamp_seconds: 3240, title: 'Chapter Five — The Girls on Bicycles', description: "The film's breath. Ordinary life made extraordinary by everything around it.",  chapter: 'Ordinary Life' },
  { timestamp_seconds: 3840, title: 'Chapter Six — After 370',              description: 'August 5, 2019. What happens to people when the politics changes around them.',  chapter: 'Present Day' },
  { timestamp_seconds: 4380, title: 'Chapter Seven — The Ideology That Failed', description: "A militant's certainty collapses. The moment the idea stops being true.",  chapter: 'Reckoning' },
  { timestamp_seconds: 4980, title: 'Epilogue — Faces in Silence',          description: 'The final section. Faces. No voiceover. The silence after everything has been said.',  chapter: 'Epilogue' },
];
